hw:
  page_size_KB: 32
  tasks_per_PE: 1           # Typical: 1 - 6
  repository_size_MB: 1
  model_description: sc     # sc (gcc) | scmod (ModelSim) | rtl (ModelSim)
  noc_buffer_size: 8        # Typical: 8, must be power of 2
  mpsoc_dimension: [4,4]    # Minimal: [2,2], must be square
  cluster_dimension: [2,2]  # Must be square
  master_location: LB       # Must be LB

apps:
  - name: pc1
    start_time_ms: 1 ms
  - name: pc2
    start_time_ms: 5 ms